Layout/EndOfLine:
  EnforcedStyle: crlf

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_special