Layout/EndOfLine:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Layout/EmptyLinesAroundClassBody:
  Enabled: false