Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/InverseMethods:
  Enabled: false
