language: ruby
rvm:
  - 2.5.5
services: mysql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake test
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database sepid_test'
bundler_args: --binstubs=./bundler_stubs
notifications:
  email: false
cache: bundler