data_method: MyDataMethods.change_status_count
ui_filters:
  - date_change_status_order
chart:
  options:
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Fecha cambio estado
      yAxes:
        - scaleLabel:
            display: true
            labelString: Cantidad
            ticks:
              beginAtZero: true