data_method: MyDataMethods.change_status_count
chart:
  options:
    scales:
      xAxes:
        - stacked: true
        - scaleLabel:
            display: true
            labelString: Estados
      yAxes:
        - stacked: true
        - scaleLabel:
            display: true
            labelString: Cantidad