data_method: MyDataMethods.orders_by_type
chart:
  options:
    scales:
      xAxes:
        - scaleLabel:
            labelString: Fecha de pedido
      yAxes:
        - scaleLabel:
            labelString: Pedidos