data_method: MyDataMethods.orders_by_type
chart:
  options:
    scales:
      xAxes:
        - stacked: true
        - scaleLabel:
            display: true
            labelString: Fecha de pedido
      yAxes:
        - stacked: true
        - scaleLabel:
            labelString: Pedidos