data_method: MyDataMethods.change_status_count
chart:
  options:
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Fecha cambio estado
      yAxes:
        - scaleLabel:
            display: true
            labelString: Cantidad